Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
    end
    config.vm.define "slave" do |slave|
      slave.vm.hostname = "slave"
    end
end
