Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/hirsute64"
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/packages.yaml"
        ansible.become = true
        ansible.verbose ="v"
#        ansible.become_user = "root"
      end
    end
    config.vm.define "slave" do |slave|
      slave.vm.hostname = "slave"
      slave.vm.provision "shell", path: "scripts/pre.sh"
    end
end
