Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.synced_folder "~/vagrant", "/mnt/vagrant",
    create: true, owner: "vagrant", group: "vagrant", id: "frontend"
end
