Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.network "forwarded_port", guest: 80, host: 8081, id: "web"
#  config.vm.network "private_network", type: "dhcp"
#  config.vm.network "private_network", ip: "1.1.1.1"
#  config.vm.network "public_network", type: "dhcp"
end
