Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.synced_folder "/nfs_share",
                          "/mnt/nfs_share", 
                          type: "nfs",
                          nfs_export: true,
                          nfs_udp: false,
                          nfs_version: 3,
                          id: "nfs",
                          linux__nfs_options: ['ro','no_subtree_check','all_squash','async']
  config.vm.network "private_network", ip: "172.28.128.5"
end
