Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.synced_folder "/tmp/rsync_share",
                          "/mnt/rsync_share", 
                          type: "rsync",
                          create: true, 
                          group: "vagrant", 
                          owner: "vagrant",
                          rsync__auto: true, 
                          id: "rsync"
  config.vm.network "private_network", ip: "172.28.128.5"
end
